# config/validator/validation.yaml

App\Entity\Measurement:
    properties:
        date:
            - NotBlank: { groups: [create, edit] }
            -   Type:
                    type: DateTimeInterface
                    groups: [ create, edit ]

        celsius:
            - NotBlank: { groups: [ create, edit] }
            - Type: { type: numeric, groups: [create, edit] }
            - Range:
                  min: -90
                  max: 60
                  groups: [new, create, edit]

        location:
            - NotNull: { groups: [create, edit] }
            - Valid:   { groups: [create, edit] }

App\Entity\Location:
    properties:
        city:
            - NotBlank: { groups: [create, edit] }
            - Length:
                  min: 1
                  max: 100
                  groups: [create, edit]

        country:
            - NotBlank: { groups: [create, edit] }
            - Choice:
                  choices: [PL, DE, FR, ES, IT, US, GB, AU, AT, AZ, BH, BD, CH, KR, RU]
                  groups: [create, edit]

        latitude:
            - NotNull: { groups: [create, edit] }
            - Type: { type: numeric, groups: [create, edit] }
            - Range:
                  min: -90
                  max: 90
                  groups: [create, edit]

        longitude:
            - NotNull: { groups: [create, edit] }
            - Type: { type: numeric, groups: [create, edit] }
            - Range:
                  min: -180
                  max: 180
                  groups: [create, edit]
